url: "" # the base hostname & protocol for your site, e.g. https://example.com

permalink: pretty
template_engine: liquid
plugins:
  - bridgetown-esbuild

environment:
  development:
    FORMSPREE_URL: "{{ site.environment.FORMSPREE_URL }}"
  production:
    FORMSPREE_URL: "{{ site.environment.FORMSPREE_URL }}"
