url: "https://escola-com-maria.pages.dev/"
permalink: pretty
template_engine: liquid

language: "pt-BR"
locale: "pt-BR"
timezone: "America/Sao_Paulo"

paths:
  static: ["images"]

environment:
  development:
    FORMSPREE_URL: "https://formspree.io/f/mqaqprqj"
  production:
    FORMSPREE_URL: "https://formspree.io/f/mqaqprqj"
