url: "https://escola-com-maria.pages.dev/"

permalink: pretty
template_engine: liquid

paths:
  static: ["images"]

environment:
  development:
    FORMSPREE_URL: "{{ site.environment.FORMSPREE_URL }}"
  production:
    FORMSPREE_URL: "{{ site.environment.FORMSPREE_URL }}"