name: Deploy diário para Cloudflare Pages

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true

      - name: Instalar dependências
        run: bundle install

      - name: Build do site Bridgetown
        run: bundle exec bridgetown build

      - name: Disparar deploy no Cloudflare Pages
        run: curl -X POST ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}